#! /bin/bash

# Default server password
PASSWORD=defaultpassword

## Note: these variables are used in the init script as well. Update in both.
# Username
USERNAME=terraria

# Terraria Directory
SOURCEDIR=/opt/tshock

# Server executable
SERVERBIN=${SOURCEDIR}/TerrariaServer.exe

# Server Config
CONFIGDIR=/etc/tshock
SERVERCONFIG=${CONFIGDIR}/server.conf

# PID
PID=/run/tshock.pid

# Current User
ME=$(whoami)

# Original Arguments
ARGS=$@
STARTINGPATH=$(pwd)

if [ "$(whoami)" != 'root' ]; then
   echo "This script must be run as root. Use \"sudo\" to accomplish this." 1>&2
   exit 1
fi

## Check to ensure tshock init file is available
if [ ! -e ./tshock ]; then
  echo "Cannot continue! The init script \"tshock\" is missing! Please copy this file to the same directory as this install script to continue."
  exit 1
fi

## Install dependencies and create users
apt-get install mono-complete dameon -y
adduser --disabled-login terraria

## Download and unpack binary
cd /opt
wget -O tshock.zip https://github.com/NyxStudios/TShock/releases/download/v4.2.10/tshock_4.2.10.zip
unzip tshock.zip -d tshock
rm tshock.zip
chown terraria: tshock
chmod -R 700 tshock    # for security of the database

## Create and configure configuration directory
mkdir /etc/tshock
chown terraria: /etc/tshock
chown -R 644 /etc/tshock


LOOPCONTROL=true
while [ ${LOOPCONTROL} == true ]
do
  read -p "Do you want the default world size to be small(1), medium(2), or large(3)? Enter 1, 2, or 3: " size
  case $size in
    1)
      LOOPCONTROL=false
      ;;
    2)
      LOOPCONTROL=false
      ;;
    3)
      LOOPCONTROL=false
      ;;
    *)
      echo "Please answer with \"1\", \"2\", or \"3\"."
      ;;
  esac
done


## Write default server.conf to /etc/tshock
if [ ! -s /etc/tshock/server.conf ]; then
contents="maxplayers=8
worldpath=${SOURCEDIR}/Terraria/Worlds/
port=7777
autocreate=${size}
worldname=autocreated_world
password=${PASSWORD}
secure=1"
fi

echo "$contents" > /etc/tshock/server.conf

echo "The password set for the server is: \"${PASSWORD}\". Remember to change it in ${SERVERCONFIG}!"

## Write tshock init script to init.d, and run update-rc.d
cd ${STARTINGPATH}
chown root: tshock
chmod 755 tshock
mv tshock /etc/init.d/tshock
update-rc.d tshock defaults 21

echo “Installation complete! You can start your server now by typing \”sudo service tshock start\”.” 
