#! /bin/bash

# Default server password
PASSWORD=defaultpassword

## Note: these variables are used in the init script as well. Update in both.
# Username

# Terraria Directory
SOURCEDIR=/opt/tshock

# Server executable
SERVERBIN=${SOURCEDIR}/TerrariaServer.exe

# Server Config
CONFIGDIR=/etc/tshock
SERVERCONFIG=${CONFIGDIR}/server.conf

# PID
PID=/run/tshock.pid

# Current User
ME=$(whoami)

# Original Arguments
ARGS=$@
STARTINGPATH=$(pwd)

## Add date to log file
echo $(date) >> ${STARTINGPATH}/InstallLog.txt

if [ "$(whoami)" != 'root' ]; then
   echo "This script must be run as root. Use \"sudo\" to accomplish this." 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
   exit 1
fi

## Check to ensure tshock init file is available
if [ ! -e ./tshock ]; then
  echo "Cannot continue! The init script \"tshock\" is missing! Please copy this file to the same directory as this install script to continue." 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
  exit 1
fi

## Install dependencies and create users
echo "Starting installation... downloading and installing dependencies" 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
apt-get install mono-complete daemon -y >> ${STARTINGPATH}/InstallLog.txt 2>&1

## Download and unpack binary
echo "Downloading binaries..." 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
cd /opt   # WARNING: THIS WILL MESS UP PATHS IF NOT CAREFUL
wget --progress=bar:force -a ${STARTINGPATH}/InstallLog.txt -O tshock.zip https://github.com/NyxStudios/TShock/releases/download/v4.2.10/tshock_4.2.10.zip
unzip -u -o tshock.zip -d tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1 
rm tshock.zip >> ${STARTINGPATH}/InstallLog.txt 2>&1
chmod -R 700 tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1   # for security of the database

cd ${STARTINGPATH}    # Return to starting directory to not mess things up 

## Create and configure configuration directory
echo "Making program directories..." 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
mkdir /etc/tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1
chmod -R 644 /etc/tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1

## Write default server.conf to /etc/tshock
if [ ! -e ${SERVERCONFIG} ]; then
  LOOPCONTROL=true
  while [ ${LOOPCONTROL} == true ]
  do
    read -p "Do you want the default world size to be small(1), medium(2), or large(3)? Enter 1, 2, or 3: " size
    case $size in
      1)
        echo "Small size world chosen." >> ${STARTINGPATH}/InstallLog.txt
        LOOPCONTROL=false
        ;;
      2)
        echo "Medium size world chosen." >> ${STARTINGPATH}/InstallLog.txt
        LOOPCONTROL=false
        ;;
      3)
        echo "Large size world chosen." >> ${STARTINGPATH}/InstallLog.txt
        LOOPCONTROL=false
        ;;
      *)
        echo "Please answer with \"1\", \"2\", or \"3\"."
        ;;
    esac
  done

# This needs to stay formatted with it's alignment to the far left
contents="maxplayers=8
world=./Terraria/Worlds/*.wld
worldpath=./Terraria/Worlds/
port=7777
autocreate=${size}
worldname=autocreated_world
password=${PASSWORD}
secure=1"
  sh -c "echo \"${contents}\" > ${SERVERCONFIG}" >> ${STARTINGPATH}/InstallLog.txt 2>&1
  chmod o-r ${SERVERCONFIG} >> ${STARTINGPATH}/InstallLog.txt 2>&1
  echo "The password set for the server is: \"${PASSWORD}\". Remember to change it in ${SERVERCONFIG}!" 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
else
    echo "A server.conf file already exists! Please consult it for the server password."
fi

ln -s ${SERVERCONFIG} ${SOURCEDIR}/server.conf >> ${STARTINGPATH}/InstallLog.txt 2>&1


## Write tshock init script to init.d, and run update-rc.d
echo "Configuring server to automatically start..." 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
cp tshock /etc/init.d/tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1
chown root: /etc/init.d/tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1
chmod 755 /etc/init.d/tshock >> ${STARTINGPATH}/InstallLog.txt 2>&1
update-rc.d tshock defaults 21 >> ${STARTINGPATH}/InstallLog.txt 2>&1 

echo "Installation complete! You can start your server and set up your first world now by typing \"sudo service tshock first-start\". Don't forget to close the server after the world is created (there's more steps!), and remember to insert the name of the world you created into the \"*.wld\" line of the screen that appears! Start your server from then on with \"sudo service tshock start\"." 2>&1 | tee -a ${STARTINGPATH}/InstallLog.txt
